# Generated by Django 4.1.7 on 2023-02-22 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenWeatherLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Дата запроса')),
                ('result', models.BooleanField(default=False, verbose_name='Результат запроса')),
                ('error', models.JSONField(blank=True, default=dict, null=True, verbose_name='Ошибка')),
            ],
            options={
                'verbose_name': 'Лог OpenWeather',
                'verbose_name_plural': 'Логи OpenWeather',
            },
        ),
        migrations.CreateModel(
            name='OpenWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='Город')),
                ('temperature', models.IntegerField(verbose_name='Температура')),
                ('latitude', models.FloatField(verbose_name='Ширина')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('sunrise', models.DateTimeField(verbose_name='Восход')),
                ('sunset', models.DateTimeField(verbose_name='Закат')),
                ('open_error', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='weather.openweatherlog')),
            ],
            options={
                'verbose_name': 'Погода OpenWeather',
                'verbose_name_plural': 'Погода OpenWeather',
            },
        ),
    ]
